### PR TITLE
Rename ROS-related .yaml to .param.yaml

### PR DESCRIPTION
**Pull request by kenji-miyake**
launcher changes for https://github.com/tier4/AutowareArchitectureProposal.iv/pull/352

### CODE REVIEW

**Comment by wep21** [comment]
@kenji-miyake Cloud you rebase?

**Comment by kenji-miyake** [comment]
Yes, I'll rebase later.

**Comment by kenji-miyake** [comment]
Rebased!

**Comment by wep21** [comment]
before
`
src/autoware/launcher/control_launch/config/mpc_follower/mpc_follower_param.yaml
src/autoware/launcher/control_launch/config/pure_pursuit/pure_pursuit_param.yaml
src/autoware/launcher/control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.yaml
src/autoware/launcher/control_launch/config/velocity_controller/velocity_controller_param.yaml
src/autoware/launcher/localization_launch/config/ndt_scan_matcher.yaml
src/autoware/launcher/planning_launch/config/adaptive_cruise_control.yaml
src/autoware/launcher/planning_launch/config/obstacle_stop_planner.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/common/motion_velocity_optimizer/motion_velocity_optimizer.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_center_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_left_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_right_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_left_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_right_bd_code.yaml
src/autoware/launcher/sensing_launch/data/traffic_light_camera.yaml
src/autoware/launcher/system_launch/config/system_monitor.param.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_customized/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_s1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x2/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx2/sensors_calibration.yaml
`
after
`
src/autoware/launcher/control_launch/config/mpc_follower/mpc_follower.param.yaml
src/autoware/launcher/control_launch/config/pure_pursuit/pure_pursuit.param.yaml
src/autoware/launcher/control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
src/autoware/launcher/control_launch/config/velocity_controller/velocity_controller.param.yaml
src/autoware/launcher/localization_launch/config/ndt_scan_matcher.param.yaml
src/autoware/launcher/planning_launch/config/adaptive_cruise_control.param.yaml
src/autoware/launcher/planning_launch/config/obstacle_stop_planner.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/common/motion_velocity_optimizer/motion_velocity_optimizer.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_center_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_left_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_right_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_left_bd_code.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_right_bd_code.yaml
src/autoware/launcher/sensing_launch/data/traffic_light_camera.yaml
src/autoware/launcher/system_launch/config/system_monitor.param.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_customized/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_s1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x2/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx2/sensors_calibration.yaml
`

**Comment by wep21** [comment]
@kenji-miyake I'm sorry, but I added livox param files in old file name style at https://github.com/tier4/autoware_launcher.iv.universe/pull/57. Could you fix them?

**Comment by kenji-miyake** [comment]
@wep21 Of course! I'll do it later.

**Comment by kenji-miyake** [comment]
@wep21 Fixed. Please check it again.

**Review by wep21 — APPROVED** [review]
LGTM.
```
❯ fdfind .yaml src/autoware/launcher
src/autoware/launcher/control_launch/config/mpc_follower/mpc_follower.param.yaml
src/autoware/launcher/control_launch/config/pure_pursuit/pure_pursuit.param.yaml
src/autoware/launcher/control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
src/autoware/launcher/control_launch/config/velocity_controller/velocity_controller.param.yaml
src/autoware/launcher/localization_launch/config/ndt_scan_matcher.param.yaml
src/autoware/launcher/planning_launch/config/adaptive_cruise_control.param.yaml
src/autoware/launcher/planning_launch/config/obstacle_stop_planner.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/common/motion_velocity_optimizer/motion_velocity_optimizer.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
src/autoware/launcher/planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_center_bd_code.param.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_left_bd_code.param.yaml
src/autoware/launcher/sensing_launch/config/aip_x1/default/livox_front_right_bd_code.param.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_left_bd_code.param.yaml
src/autoware/launcher/sensing_launch/config/aip_xx1/default/livox_front_right_bd_code.param.yaml
src/autoware/launcher/sensing_launch/data/traffic_light_camera.yaml
src/autoware/launcher/system_launch/config/system_monitor.param.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_customized/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_s1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_x2/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensor_kit_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx1/sensors_calibration.yaml
src/autoware/launcher/vehicle_launch/config/default/aip_xx2/sensors_calibration.yaml
```
```
❯ ag '\.yaml' src/autoware/launcher
src/autoware/launcher/sensing_launch/launch/aip_s1/gnss.launch.xml
11:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/sensing_launch/launch/velodyne_VLS128.launch.xml
7:  <arg name="calibration" default="$(find-pkg-share velodyne_pointcloud)/params/VLS-128_FS1.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_x2/camera.launch.xml
15:        <param name="camera_info_url" value="$(find-pkg-share sensing_launch)/data/traffic_light_camera.yaml" />

src/autoware/launcher/sensing_launch/launch/aip_x2/gnss.launch.xml
11:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_xx2/camera.launch.xml
15:        <param name="camera_info_url" value="$(find-pkg-share sensing_launch)/data/traffic_light_camera.yaml" />

src/autoware/launcher/sensing_launch/launch/velodyne_VLP16.launch.xml
7:  <arg name="calibration" default="$(find-pkg-share velodyne_pointcloud)/params/VLP16db.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_x1/lidar.launch.xml
28:        <arg name="bd_code_param_path" value="$(find-pkg-share sensing_launch)/config/aip_x1/$(env VEHICLE_ID default)/livox_front_left_bd_code.param.yaml" />
40:        <arg name="bd_code_param_path" value="$(find-pkg-share sensing_launch)/config/aip_x1/$(env VEHICLE_ID default)/livox_front_center_bd_code.param.yaml" />
52:        <arg name="bd_code_param_path" value="$(find-pkg-share sensing_launch)/config/aip_x1/$(env VEHICLE_ID default)/livox_front_right_bd_code.param.yaml" />

src/autoware/launcher/sensing_launch/launch/aip_xx2/gnss.launch.xml
11:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/sensing_launch/launch/velodyne_VLP32C.launch.xml
7:  <arg name="calibration" default="$(find-pkg-share velodyne_pointcloud)/params/VeloView-VLP-32C.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_customized/gnss.launch.xml
11:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_x1/gnss.launch.xml
12:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_s1/camera.launch.xml
15:        <param name="camera_info_url" value="$(find-pkg-share sensing_launch)/data/traffic_light_camera.yaml" />

src/autoware/launcher/autoware_launch/launch/planning_simulator.launch.xml
21:    <arg name="vehicle_param_file" value="$(find-pkg-share $(var vehicle_model)_description)/config/vehicle_info.param.yaml"/>
46:    <arg name="vehicle_param_file" value="$(find-pkg-share $(var vehicle_model)_description)/config/vehicle_info.param.yaml"/>
51:    <arg name="vehicle_param_file" value="$(find-pkg-share $(var vehicle_model)_description)/config/vehicle_info.param.yaml"/>

src/autoware/launcher/sensing_launch/launch/aip_xx1/lidar.launch.xml
76:        <arg name="bd_code_param_path" value="$(find-pkg-share sensing_launch)/config/aip_xx1/$(env VEHICLE_ID default)/livox_front_left_bd_code.param.yaml" />
88:        <arg name="bd_code_param_path" value="$(find-pkg-share sensing_launch)/config/aip_xx1/$(env VEHICLE_ID default)/livox_front_right_bd_code.param.yaml" />

src/autoware/launcher/sensing_launch/launch/aip_customized/camera.launch.xml
15:        <param name="camera_info_url" value="$(find-pkg-share sensing_launch)/data/traffic_light_camera.yaml" />

src/autoware/launcher/sensing_launch/launch/aip_xx1/gnss.launch.xml
11:      <param from="$(find-pkg-share ublox_gps)/c94_f9p_rover.yaml"/>

src/autoware/launcher/vehicle_launch/launch/vehicle_interface.launch.xml
14:    <arg name="simulator_model" default="$(var vehicle_model_pkg)/config/simulator_model.param.yaml" />

src/autoware/launcher/system_launch/launch/system.launch.xml
12:        <arg name="config_file" value="$(find-pkg-share system_launch)/config/system_monitor.param.yaml"/>
19:        <arg name="config_file" value="$(find-pkg-share autoware_state_monitor)/config/autoware_state_monitor.param.yaml" />
24:        <arg name="config_file" value="$(find-pkg-share autoware_state_monitor)/config/autoware_state_monitor.planning_simulation.param.yaml" />
31:        <arg name="config_file" value="$(find-pkg-share autoware_error_monitor)/config/autoware_error_monitor.param.yaml" />
36:        <arg name="config_file" value="$(find-pkg-share autoware_error_monitor)/config/autoware_error_monitor.planning_simulation.param.yaml" />
42:      <arg name="config_file" value="$(find-pkg-share emergency_handler)/config/emergency_handler.param.yaml" />

src/autoware/launcher/control_launch/launch/control.launch.xml
10:  <arg name="mpc_follower_param_path" default="$(find-pkg-share control_launch)/config/mpc_follower/mpc_follower.param.yaml"/>
11:  <arg name="pure_pursuit_param_path" default="$(find-pkg-share control_launch)/config/pure_pursuit/pure_pursuit.param.yaml"/>
12:  <arg name="velocity_controller_param_path" default="$(find-pkg-share control_launch)/config/velocity_controller/velocity_controller.param.yaml"/>
13:  <arg name="vehicle_cmd_gate_param_path" default="$(find-pkg-share control_launch)/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml"/>

src/autoware/launcher/localization_launch/launch/pose_estimator/pose_estimator.launch.xml
13:    <arg name="param_file" value="$(find-pkg-share localization_launch)/config/ndt_scan_matcher.param.yaml" />

src/autoware/launcher/planning_launch/launch/scenario_planning/scenario_planning.launch.xml
21:      <arg name="param_path" value="$(find-pkg-share planning_launch)/config/scenario_planning/common/motion_velocity_optimizer/motion_velocity_optimizer.param.yaml"/>

src/autoware/launcher/planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
9:      <arg name="param_path" value="$(find-pkg-share planning_launch)/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml"/>
23:      <arg name="param_path" value="$(find-pkg-share planning_launch)/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml"/>
43:      <arg name="acc_param_file" value="$(find-pkg-share planning_launch)/config/adaptive_cruise_control.param.yaml" />
44:      <arg name="param_file" value="$(find-pkg-share planning_launch)/config/obstacle_stop_planner.param.yaml" />
```

**Pull request merged**
