### PR TITLE
add clock_publisher and autoware_version

### PR DESCRIPTION
**Pull request by mitsudome-r**
Add newly created packages to launch files.

### CODE REVIEW

**Comment by wep21** [comment]
I think it's better to add clock publisher as exec_depend in package.xml.

**Comment by mitsudome-r** [comment]
> I think it's better to add clock publisher as exec_depend in package.xml.

done.

**Review by isamu-takagi — DISMISSED** [review]
LGTM

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
