### PR TITLE
fix velodyne launch

### PR DESCRIPTION
**Pull request by taichiH**
I fixed velodyne launch to pass vehicle_param_file and mirror_param_file.

### CODE REVIEW

**Comment by taichiH** [comment]
Sorry please do not merge now. I have a bit more modification items.

**Comment by taichiH** [comment]
It's ready for review.

**Review by kenji-miyake — APPROVED** [review]

**Comment by kenji-miyake** [comment]
LGTM, but I'd like to wait for @wep21 's comment.

**Comment by wep21** [comment]
Is it correct that the target branch is `ros2-v0.8.0-beta`?

**Comment by taichiH** [comment]
I've changed base branch.
We need to resolve v0.9 and v0.8 confilict. I'll fix it.

**Comment by taichiH** [comment]
@wep21 @kenji-miyake 
please review sync pr.
https://github.com/tier4/autoware_launcher.iv.universe/pull/74

**Comment by kenji-miyake** [comment]
@taichiH Can you rebase this PR on ros2-v0.9.0-beta?

**Comment by taichiH** [comment]
Change bese branch to v0.9.0 and resolve conflict.

**Review by wep21 — APPROVED** [review]
LGTM
```
❯ ros2 launch sensing_launch velodyne_node_container.launch.py -s
Arguments (pass arguments as '<name>:=<value>'):

    'model':
        no description given

    'launch_driver':
        no description given
        (default: 'True')

    'calibration':
        no description given

    'device_ip':
        no description given
        (default: '192.168.1.201')

    'scan_phase':
        no description given
        (default: '0.0')

    'base_frame':
        no description given
        (default: 'base_link')

    'container_name':
        no description given
        (default: 'velodyne_composable_node_container')

    'min_range':
        no description given

    'max_range':
        no description given

    'pcap':
        no description given
        (default: '')

    'port':
        no description given
        (default: '2368')

    'read_fast':
        no description given
        (default: 'False')

    'read_once':
        no description given
        (default: 'False')

    'repeat_delay':
        no description given
        (default: '0.0')

    'rpm':
        no description given
        (default: '600.0')

    'laserscan_ring':
        no description given
        (default: '-1')

    'laserscan_resolution':
        no description given
        (default: '0.007')

    'num_points_thresholds':
        no description given
        (default: '300')

    'invalid_intensity':
        no description given

    'frame_id':
        no description given
        (default: 'velodyne')

    'gps_time':
        no description given
        (default: 'False')

    'input_frame':
        no description given
        (default: LaunchConfig('base_frame'))

    'output_frame':
        no description given
        (default: LaunchConfig('base_frame'))

    'vehicle_param_file':
        no description given

    'vehicle_mirror_param_file':
        no description given
```
```
❯ ros2 launch sensing_launch velodyne_VLP16.launch.xml -s
Arguments (pass arguments as '<name>:=<value>'):

    'launch_driver':
        no description given
        (default: 'true')

    'model':
        no description given
        (default: 'VLP16')

    'calibration':
        no description given
        (default: FindPackageShare(pkg='velodyne_pointcloud') + '/params/VLP16db.yaml')

    'max_range':
        no description given
        (default: '130.0')

    'min_range':
        no description given
        (default: '0.4')

    'invalid_intensity':
        no description given
        (default: '[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]')

    'sensor_frame':
        no description given
        (default: 'velodyne')

    'device_ip':
        no description given
        (default: '192.168.1.201')

    'port':
        no description given
        (default: '2368')

    'scan_phase':
        no description given
        (default: '0.0')

    'vehicle_param_file':
        no description given

    'vehicle_mirror_param_file':
        no description given
```
```
❯ ros2 launch sensing_launch velodyne_VLP32C.launch.xml -s
Arguments (pass arguments as '<name>:=<value>'):

    'launch_driver':
        no description given
        (default: 'true')

    'model':
        no description given
        (default: '32C')

    'calibration':
        no description given
        (default: FindPackageShare(pkg='velodyne_pointcloud') + '/params/VeloView-VLP-32C.yaml')

    'max_range':
        no description given
        (default: '200.0')

    'min_range':
        no description given
        (default: '0.4')

    'invalid_intensity':
        no description given
        (default: '[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]')

    'sensor_frame':
        no description given
        (default: 'velodyne')

    'device_ip':
        no description given
        (default: '192.168.1.201')

    'port':
        no description given
        (default: '2368')

    'scan_phase':
        no description given
        (default: '0.0')

    'vehicle_param_file':
        no description given

    'vehicle_mirror_param_file':
        no description given
```
```
❯ ros2 launch sensing_launch velodyne_VLS128.launch.xml -s
Arguments (pass arguments as '<name>:=<value>'):

    'launch_driver':
        no description given
        (default: 'true')

    'model':
        no description given
        (default: 'VLS128')

    'calibration':
        no description given
        (default: FindPackageShare(pkg='velodyne_pointcloud') + '/params/VLS-128_FS1.yaml')

    'max_range':
        no description given
        (default: '250.0')

    'min_range':
        no description given
        (default: '0.5')

    'invalid_intensity':
        no description given
        (default: '[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]')

    'sensor_frame':
        no description given
        (default: 'velodyne')

    'device_ip':
        no description given
        (default: '192.168.1.201')

    'port':
        no description given
        (default: '2368')

    'scan_phase':
        no description given
        (default: '0.0')

    'vehicle_param_file':
        no description given

    'vehicle_mirror_param_file':
        no description given
```

**Pull request merged**
